runtime: go
api_version: go1

handlers:
    - url: /build/app.js
      static_files: build/app.js
      upload: build/app.js

    - url: /admin/.*
      script: _go_app
      login: admin

    - url: /.*
      script: _go_app

includes:
    - ./skip_files.yaml
